# Generated by Django 3.0.8 on 2021-05-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingspot',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='huntingspot',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='huntingspot',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='huntingspot',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='huntingspot',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='huntingspot',
            name='image_6',
        ),
    ]
