# Generated by Django 3.0.8 on 2021-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210508_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingspot',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
