# Generated by Django 3.0.8 on 2021-05-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210508_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('spot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='map.HuntingSpot')),
            ],
        ),
    ]
