# Generated by Django 3.0.8 on 2021-05-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_spotimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
