# Generated by Django 3.0.8 on 2021-05-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210509_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotimages',
            old_name='spot',
            new_name='huntingspot',
        ),
    ]
