# Generated by Django 3.0.8 on 2021-05-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210509_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimages',
            name='huntingspot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='map.HuntingSpot'),
        ),
    ]
