# Generated by Django 3.0.8 on 2021-05-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20210510_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimages',
            name='huntingspot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map.HuntingSpot'),
        ),
    ]
