# Generated by Django 3.0.8 on 2021-05-10 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20210510_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('bedroms', models.IntegerField(blank=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField(blank=True)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='sleep/')),
                ('photo_1', models.ImageField(blank=True, upload_to='sleep/')),
                ('photo_2', models.ImageField(blank=True, upload_to='sleep/')),
                ('photo_3', models.ImageField(blank=True, upload_to='sleep/')),
                ('photo_4', models.ImageField(blank=True, upload_to='sleep/')),
                ('photo_5', models.ImageField(blank=True, upload_to='sleep/')),
                ('photo_6', models.ImageField(blank=True, upload_to='sleep/')),
                ('is_publish', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='map.HuntingSpot')),
            ],
        ),
    ]
