# Generated by Django 3.0.8 on 2021-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200715_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingspot',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
