# Generated by Django 3.0.8 on 2021-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20210510_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='bedroms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
