# Generated by Django 3.0.8 on 2021-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_huntingspot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingspot',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
