# Generated by Django 3.0.8 on 2021-05-08 08:26

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20210508_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=map.models.get_upload_path),
        ),
    ]
