# Generated by Django 3.0.8 on 2021-05-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20210521_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingspot',
            name='animals',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Animal'),
        ),
    ]
