# Generated by Django 3.0.8 on 2021-05-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20210521_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingspot',
            name='animals',
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='animals',
            field=models.ManyToManyField(blank=True, null=True, to='map.Animal'),
        ),
    ]
