# Generated by Django 3.0.8 on 2021-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20210522_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
