# Generated by Django 3.0.8 on 2021-05-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_auto_20210524_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingspot',
            name='sleeps',
        ),
        migrations.AddField(
            model_name='huntingspot',
            name='sleeps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.Sleep'),
        ),
    ]
