# Generated by Django 3.0.8 on 2021-05-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_auto_20210524_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingspot',
            name='sleeps',
        ),
        migrations.AddField(
            model_name='sleep',
            name='huntingspot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='map.HuntingSpot'),
            preserve_default=False,
        ),
    ]
