# Generated by Django 3.0.8 on 2021-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_auto_20210524_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
